version: "3.8"

services:
  postgres:
    container_name: postgres_greenfy
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-postgres_greenfy-to-do
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src